mysql.username=root
mysql.password=mysql

mysql.host=mysql
mysql.port=3306

mysql.database.import=ad
mysql.tables.import=

is.seperated.tables=0

hdfs.uri=hdfs://namenode:8020

import_out_dir=/opt/datax/job/import

# mysql.database.export=ad_report
# mysql.tables.export=
# export_out_dir=/opt/datax/job/export