a1.sources = r1
a1.channels = c1

# Tail node1 + node2 access.log
a1.sources.r1.type = TAILDIR
a1.sources.r1.filegroups = f1 f2
a1.sources.r1.filegroups.f1 = /logs/node1/access\.log
a1.sources.r1.filegroups.f2 = /logs/node2/access\.log
a1.sources.r1.positionFile = /flume-data/taildir_position.json

# Kafka Channel
a1.channels.c1.type = org.apache.flume.channel.kafka.KafkaChannel
a1.channels.c1.kafka.bootstrap.servers = kafka:9092
a1.channels.c1.kafka.topic = ad_log
a1.channels.c1.parseAsFlumeEvent = false

# Bind source to channel
a1.sources.r1.channels = c1