# =========================
# Components
# =========================
a1.sources = r1
a1.channels = c1
a1.sinks = k1


# =========================
# Kafka Source
# =========================
a1.sources.r1.type = org.apache.flume.source.kafka.KafkaSource

a1.sources.r1.kafka.bootstrap.servers = kafka:9092
a1.sources.r1.kafka.topics = ad_log

a1.sources.r1.batchSize = 5000
a1.sources.r1.batchDurationMillis = 2000

a1.sources.r1.interceptors = i1
a1.sources.r1.interceptors.i1.type = com.atguigu.ad.flume.interceptor.TimestampInterceptor$Builder


# =========================
# File Channel
# =========================
a1.channels.c1.type = file

a1.channels.c1.checkpointDir = /flume-data/checkpoint
a1.channels.c1.dataDirs = /flume-data/data

a1.channels.c1.capacity = 1000000
a1.channels.c1.keep-alive = 6


# =========================
# HDFS Sink
# =========================
a1.sinks.k1.type = hdfs

a1.sinks.k1.hdfs.path = hdfs://namenode:8020/origin_data/ad/log/ad_log/%Y-%m-%d
a1.sinks.k1.hdfs.useLocalTimeStamp = false

a1.sinks.k1.hdfs.filePrefix = log

a1.sinks.k1.hdfs.rollInterval = 10
a1.sinks.k1.hdfs.rollSize = 134217728
a1.sinks.k1.hdfs.rollCount = 0

a1.sinks.k1.hdfs.fileType = DataStream


# =========================
# Connect
# =========================
a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1